#!/bin/env bash

# mail@iarom.org Iarom Madden

_ini() {
    declare -rg cmd=$1 && shift 1
    declare -rg cfg_notmuch="/home/$USER/.config/notmuch/notmuchrc"
    declare -rg cfg_mbsync="/home/$USER/.config/isync/isyncrc"
}


_remote_sync_run() { 
    
    STATE="$(nmcli networking connectivity)"
    [ ${STATE} = 'full' ] || { echo "No internet connection."; exit 1; }
    mbsync -c "${cfg_mbsync}" --all
    echo "Notmuch:"
    notmuch --config="${cfg_notmuch}" new
} ##--quiet >> /dev/null


_remote_sync() {
  _remote_sync_ini1
  _remote_sync_run
}


_main() {

    _ini ${@}

    case ${cmd} in
        sync)       _remote_sync ;;
        md2html)     ;; #?
    esac
}


_main "${@}"

